// AI Recommendation Component
// Displays the AI's investment recommendation (Buy, Hold, or Sell) along with
// the reasoning behind the decision.

import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { TrendingUp, Shield, TrendingDown, AlertTriangle } from "lucide-react";

interface AIRecommendationCardProps {
  recommendation: string;
  insight: string;
}

const AIRecommendationCard: React.FC<AIRecommendationCardProps> = ({
  recommendation,
  insight,
}) => {
  // Determine what type of recommendation we're showing
  const isBuy = recommendation.toLowerCase() === "buy";
  const isSell = recommendation.toLowerCase() === "sell";

  // Choose appropriate styling based on recommendation type
  const getRecommendationStyle = () => {
    if (isBuy) {
      return {
        bgColor: "bg-green-50",
        borderColor: "border-l-green-500",
        textColor: "text-green-700",
        icon: TrendingUp,
        badgeStyle: "bg-green-100 text-green-800"
      };
    } else if (isSell) {
      return {
        bgColor: "bg-red-50",
        borderColor: "border-l-red-500",
        textColor: "text-red-700",
        icon: TrendingDown,
        badgeStyle: "bg-red-100 text-red-800"
      };
    } else {
      return {
        bgColor: "bg-blue-50",
        borderColor: "border-l-blue-500",
        textColor: "text-blue-700",
        icon: Shield,
        badgeStyle: "bg-blue-100 text-blue-800"
      };
    }
  };

  const style = getRecommendationStyle();
  const RecommendationIcon = style.icon;

  return (
    <Card className={`${style.bgColor} border-l-4 ${style.borderColor}`}>
      <CardHeader className="pb-3">
        <CardTitle className="text-lg font-semibold text-gray-800 flex items-center space-x-2">
          <RecommendationIcon size={20} className={style.textColor} />
          <span>AI Recommendation</span>
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-0">
        <div className="flex items-center justify-between mb-4">
          <span className={`text-3xl font-bold ${style.textColor}`}>
            {recommendation.toUpperCase()}
          </span>
          <span className={`px-3 py-1 rounded-full text-sm font-medium ${style.badgeStyle}`}>
            {recommendation}
          </span>
        </div>

        <div className="mb-4">
          <h4 className="text-sm font-semibold text-gray-700 mb-2">
            AI Reasoning:
          </h4>
          <p className="text-sm text-gray-600 leading-relaxed">
            {insight || "No detailed reasoning provided."}
          </p>
        </div>

        {/* Disclaimer */}
        <div className="mt-4 pt-4 border-t border-gray-200">
          <div className="flex items-start space-x-2">
            <AlertTriangle size={16} className="text-orange-500 mt-0.5 flex-shrink-0" />
            <div className="text-xs text-gray-600">
              <p className="font-medium mb-1">Important Disclaimer:</p>
              <p>
                This recommendation is generated by AI based on available data and should not 
                be considered as professional financial advice. Always conduct your own research 
                and consider consulting with a qualified financial advisor before making investment decisions.
              </p>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default AIRecommendationCard;
